name: Build and Deploy the Vue JS project

on:
  push:
    branches: main
  workflow_dispatch:
env:
  VITE_APP_TEST_ENV: ${{ vars.VITE_APP_TEST_ENV }}

jobs: 
  build-for-development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      
      - name: Print VITE_APP_TEST_ENV
        run: |
          echo VITE_APP_TEST_ENV directly from github = ${{ vars.VITE_APP_TEST_ENV }}
          echo VITE_APP_TEST_ENV from environment of runner = $VITE_APP_TEST_ENV
      
      - name: Installing project dependencies
        run: npm install

      - name: Building the project
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: vue-build
          path: ./dist