name: Build and Deploy the Vue JS project

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      
      - name: Installing project dependencies
      - run: npm install

      - name: Building the project
      - run: npm run build

    - uses: actions/upload-artifact@v3
      with:
        name: vue-build
        path: ./dist